# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: capas-jornais

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod

plugins:
  - serverless-plugin-include-dependencies

  # The `functions` block defines what code to deploy
functions:
  newspapers:
    handler: handler.getNewspapers
    # The `events` block defines how to trigger the handler.getNewspapers code
    events:
      - schedule: cron(15 0 * * ? *)
      - schedule: cron(25 8 * * ? *)
